### ISSUE TITLE
Results from get_associated_ws_objects not stable with different limits

### ISSUE THREAD

**Issue by eapearson** [kbaseapps/ontology_api#15]
The results of the call to `get_associated_ws_objects` results in a structure like (this is snipped from an actual result, converted to yaml for readability)

```yaml
- results:
  - features:
    - feature_id: gene00095-v1.0-hybrid
      updated_at: 1579214555270
    - feature_id: gene00123-v1.0-hybrid
      updated_at: 1579214555280
    - feature_id: gene00125-v1.0-hybrid
      updated_at: 1579214555281
    - feature_id: gene00126-v1.0-hybrid
      updated_at: 1579214555281
    - feature_id: gene00408-v1.0-hybrid
      updated_at: 1579214555382
    - feature_id: gene00622-v1.0-hybrid
      updated_at: 1579214555445
    ws_obj:
      name: Fvesca_PhytozomeV11_v1.1
      object_id: 36915
      version: 4
      workspace_id: 4258
  - features:
    - feature_id: Thecc1EG047018
      updated_at: 1579225773978
    - feature_id: Thecc1EG047047
      updated_at: 1579225773986
    - feature_id: Thecc1EG047083
      updated_at: 1579225773997
    - feature_id: Thecc1EG047100
      updated_at: 1579225774003
    ws_obj:
      name: Tcacao_PhytozomeV11_v1.1
      object_id: 36981
      version: 3
      workspace_id: 4258
```

In other "words", the results is a list of objects each with features linked to the term.  In this example, the offset is 0 and the limit 10.

When used in the ui, this is flatted to present a table of objects and features.

This ticket will not discuss whether this is a good design nor not.

The problem is that the features included per object change depending on the range requested.

The following example is from the same term as above, but with the range (0, 15). Note that the first genome object now contains 10 features (in the previous example it was 6), and the second has 5 (in the previous example 4).

```yaml
---
result:
- results:
  - features:
    - feature_id: gene00095-v1.0-hybrid
      updated_at: 1579214555270
    - feature_id: gene00123-v1.0-hybrid
      updated_at: 1579214555280
    - feature_id: gene00125-v1.0-hybrid
      updated_at: 1579214555281
    - feature_id: gene00126-v1.0-hybrid
      updated_at: 1579214555281
    - feature_id: gene00408-v1.0-hybrid
      updated_at: 1579214555382
    - feature_id: gene00622-v1.0-hybrid
      updated_at: 1579214555445
    - feature_id: gene00662-v1.0-hybrid
      updated_at: 1579214555459
    - feature_id: gene00664-v1.0-hybrid
      updated_at: 1579214555460
    - feature_id: gene00708-v1.0-hybrid
      updated_at: 1579214555475
    - feature_id: gene00715-v1.0-hybrid
      updated_at: 1579214555478
    ws_obj:
      name: Fvesca_PhytozomeV11_v1.1
      object_id: 36915
      version: 4
      workspace_id: 4258
  - features:
    - feature_id: Thecc1EG046951
      updated_at: 1579225773960
    - feature_id: Thecc1EG047018
      updated_at: 1579225773978
    - feature_id: Thecc1EG047047
      updated_at: 1579225773986
    - feature_id: Thecc1EG047083
      updated_at: 1579225773997
    - feature_id: Thecc1EG047100
      updated_at: 1579225774003
    ws_obj:
      name: Tcacao_PhytozomeV11_v1.1
      object_id: 36981
      version: 3
      workspace_id: 4258
```

I'm not sure what is going on here. After a quick look with a limit of 1000, it looks like the objects are ordered by object id, and the features are ordered by feature id.

Anyway, this is the issue -- it is not reasonable to have the results inconsistent when different limits are used.

But clearly there should be some discussion of the best way to represent the linked objects and features which preserves both stable ordering and is also useful to users. E.g. is it really useful to give the user simply a list of 100,000 features to browser through?
